---
title: "about"
output: html_document
---


#### About 

This web application uses a joint frailty-logistic predictive model based on the 3 clinical trials to predict individualized rate and severity of exacerbations. 

Please refer to the manuscript for more details on the structure of the model and the validation process.

#### User Manual

For more information about the model and how to access it, please refer to the [ACCEPT user manual](https://resplab.github.io/acceptManual/section-introduction.html). 

#### Citation

Adibi A, Sin DD, Safari A, Johnson KM, Aaron SD, FitzGerald JM, Sadatsafavi M. The Acute COPD Exacerbation Prediction Tool (ACCEPT): a modelling study. The Lancet Respiratory Medicine. 2020 Oct 1;8(10):1013-21. doi:[10.1016/S2213-2600(19)30397-2](https://doi.org/10.1016/S2213-2600%2819%2930397-2)

#### Bug Report

Please report bugs and issues [here] (https://github.com/resplab/acceptShiny/issues).

                         
#### Credits

ACCEPT is created by [Amin Adibi](http://resp.core.ubc.ca/team/Amin_Adibi),  [Abdollah Safari](http://resp.core.ubc.ca/team/Abdollah_Safari), [Kate Johnson](http://resp.core.ubc.ca/team/Kate_Johnson), [Mark FitzGerald](https://www.vchri.ca/researchers/mark-fitzgerald), [Don Sin](https://www.hli.ubc.ca/profile/sin/don), and [Mohsen Sadatsafavi](http://resp.core.ubc.ca/team/Mohsen_Sadatsafavi) at the University of British Columbia. 

